version: '3.0'
services:
  db:
    image: postgres:10
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'challenge'

  app:
    build: .
    ports:
      - '8080:8080'
    environment:
      DB_HOST: 'db'
      DB_USER: 'postgres'
      DB_PASSWORD: 'postgres'
      DB_NAME: 'challenge'
      PORT: 8080
    depends_on:
      - db
